Exception: in kbd-chooser KBD-ARCHS needs to be translated with KBD-ARCHS-L10N
git-svn-id: svn://svn.debian.org/svn/d-i/trunk@32258 48c42b26-1dd6-0310-b98f-a58d8bce7237